set(QFLUENT_VERSION_MAJOR 1)
set(QFLUENT_VERSION_MINOR 0)
set(QFLUENT_VERSION_PATCH 0)
if(EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/.git")
  execute_process(
    COMMAND git rev-parse --short HEAD
    WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}
    OUTPUT_VARIABLE QFLUENT_VERSION_TAG
    OUTPUT_STRIP_TRAILING_WHITESPACE
)
endif()
if(NOT QFLUENT_VERSION_TAG)
  set(QFLUENT_VERSION_TAG 00000000)
endif()
set(QFLUENT_VERSION_TAG_HEX 0x${QFLUENT_VERSION_TAG})
set(QFLUENT_VERSION_TAG ${QFLUENT_VERSION_TAG} CACHE STRING "Git Tag of QFluent")
set(QFLUENT_VERSION ${QFLUENT_VERSION_MAJOR}.${QFLUENT_VERSION_MINOR}.${QFLUENT_VERSION_PATCH} CACHE STRING "Version of QFluent")
